//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int AddressId { get; set; }
        public int UserId { get; set; }
        public string Line1 { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
