//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int ReviewId { get; set; }
        public string ReviewCode { get; set; }
        public int OrderItemId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Rating { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
